"""Constants for Media Player Template."""

DOMAIN = "media_player_template"

CONF_STATE_TEMPLATE = "state_template"
CONF_TITLE_TEMPLATE = "title_template"
CONF_ARTIST_TEMPLATE = "artist_template"
CONF_ALBUM_TEMPLATE = "album_template"
CONF_THUMBNAIL_TEMPLATE = "thumbnail_template"
CONF_VOLUME_TEMPLATE = "volume_template"
CONF_MUTED_TEMPLATE = "muted_template"
CONF_SOUND_MODE_TEMPLATE = "sound_mode_template"
CONF_SOURCE_TEMPLATE = "source_template"
CONF_POSITION_TEMPLATE = "position_template"
CONF_DURATION_TEMPLATE = "duration_template"
CONF_MEDIA_TYPE_TEMPLATE = "media_type_template"

CONF_PLAY_SCRIPT = "play_script"
CONF_PAUSE_SCRIPT = "pause_script"
CONF_STOP_SCRIPT = "stop_script"
CONF_NEXT_SCRIPT = "next_script"
CONF_PREVIOUS_SCRIPT = "previous_script"
CONF_VOLUME_UP_SCRIPT = "volume_up_script"
CONF_VOLUME_DOWN_SCRIPT = "volume_down_script"
CONF_SET_VOLUME_SCRIPT = "set_volume_script"
CONF_MUTE_SCRIPT = "mute_script"
CONF_TURN_ON_SCRIPT = "turn_on_script"
CONF_TURN_OFF_SCRIPT = "turn_off_script"
CONF_SELECT_SOURCE_SCRIPT = "select_source_script"
CONF_SELECT_SOUND_MODE_SCRIPT = "select_sound_mode_script"
CONF_PLAY_MEDIA_SCRIPT = "play_media_script"
CONF_SEEK_SCRIPT = "seek_script"
